apiVersion: apps/v1
kind: Deployment
metadata:
  name: read-dep
  labels:
    app: dep
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dep
  template:
    metadata:
      labels:
        app: dep
    spec:
      containers:
      - name: c1
        image: alpine
        args:
        - /bin/sh
        - -c
        #- touch /tmp/healthy; sleep 30; rm -f /tmp/healthy; sleep 600
        - sleep 10; touch /1.txt; sleep 50; rm -f 1.txt; sleep 50
        livenessProbe:
          exec:
            command:
            - ls
            - -l
            - 1.txt
          initialDelaySeconds: 12
          periodSeconds: 12
        readinessProbe:
          exec:
            command:
            - ls
            - -l
            - 1.txt
          initialDelaySeconds: 10 
          periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: dep-serv
spec:
  selector:
    app: dep
  ports:
  - port: 80
