apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep1
  labels:
    app: dep
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dep
  template:
    metadata:
      labels:
        app: dep
    spec:
      containers:
      - name: c1
        image: nginx
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 3
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 8
          periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: dep-serv
spec:
  selector:
    app: dep
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 32000
