apiVersion: v1
kind: Pod
metadata:
  name: pod1
spec:
  containers:
  - name: db
    image: mysql
    env:
    - name:  MYSQL_ROOT_PASSWORD
      value: root
    volumeMounts:
    - name: vol1
      mountPath: /var/lib
  volumes:
  - name: vol1
    hostPath:
      path: /pod-db
      type: DirectoryOrCreate
