apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: nginx
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
      volumeMounts:
        - name: nginx-storage
          mountPath: /usr/share/nginx/html
    - name: ubuntu
      image: ubuntu:18.04
      command: ["/bin/bash"]
      args: ["-c","while true;do date>>/var/tmp/index.html ; sleep 10; done"]
      volumeMounts:
        - name: nginx-storage
          mountPath: /var/tmp
  volumes:
    - name: nginx-storage
      emptyDir: {}
