apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-dep
  namespace: nginx-ns
  labels:
    dep: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      dep: nginx
  template:
    metadata:
      name: nginx-pod
      labels:
        dep: nginx
    spec:
      containers:
        - name: nginx-container
          image: httpd
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: nginx-ns
  labels:
    service: nginx
spec:
  selector:
     dep: nginx
  ports:
    - protocol: TCP
      port: 8989
      targetPort: 80
  

