apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: host-port
  name: host-port
spec:
  containers:
  - image: nginx
    name: host-port
    ports:
    - containerPort: 80
      hostPort: 8080
      protocol: TCP
      name: http
