apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep1
  labels:
    app: dep1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dep1
  template:
    metadata:
      labels:
        app: dep1
    spec:
      containers:
      - name: c1
        image: nginx
        ports:
        - containerPort: 80
      nodeName: node2
---
apiVersion: v1
kind: Service
metadata:
   name: dep-serv
spec:
  selector:
    app: dep1
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30002

