apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: pod
  name: p1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pod
  template:
    metadata:
      labels:
        app: pod
    spec:
      containers:
      - image: mysql:5.7
        name: p1
        env:
        - name: MYSQL_ROOT_PASSWORD
          #value: root123
          valueFrom:
            configMapKeyRef:
              name: cmap
              key: WORDPRESS_DB_PASSWORD
        - name: MYSQL_DATABASE
          value: wpdb
        ports: 
        - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: db-svc
spec:
  selector:
    app: pod
  ports:
  - port: 3306
    targetPort: 3306
