apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: wp-dep
  name: wp-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wp-dep
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: wp-dep
    spec:
      containers:
      - image: wordpress
        name: wordpress
        resources: {}
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: cmap
---
apiVersion: v1
kind: Service
metadata:
  name: wp-svc
spec:
  selector:
    app: wp-dep
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30001
