apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nw-pod
  name: nw-pod
spec:
  containers:
  - image: nginx:latest
    name: c1
    resources: {}
  - name: c2
    image: nginx:1.19.0
  dnsPolicy: ClusterFirst
  restartPolicy: Always

