apiVersion: v1
kind: Service
metadata:
  name: hs-ss-nginx
spec:
  clusterIP: None
  selector:
    app: ss
  ports:
  - port: 80
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ss-nginx
  labels:
    app: ss
spec:
  serviceName: hs-ss-nginx
  replicas: 3
  selector:
    matchLabels:
      app: ss
  template:
    metadata:
      labels:
        app: ss
    spec:
      containers:
      - name: c1
        image: nginx
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: ss-cl-svc
spec:
  selector:
    app: ss
  ports:
  - port: 80
    targetPort: 80
