apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: git-alp
  name: git-alp
spec:
  containers:
  - name: ci
    image: alpine
    command: ["sleep","infinity"]
    args:
    - "mkdir"
    - "html"
