apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongoexpress-dep
  labels:
    app: mongoexpress
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mongoexpress
  template:
    metadata:
      name: mongoexpress-pod
      labels:
        app: mongoexpress
    spec:
      containers:
        - name: mongoexpress-cotainer
          image: mongo-express:0.54.0
          ports:
            - containerPort: 8081
          env:
            - name: ME_CONFIG_MONGODB_ADMINUSERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongodb_username
            - name: ME_CONFIG_MONGODB_ADMINPASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongodb_userpasswd
            - name: ME_CONFIG_MONGODB_SERVER
              valueFrom:
                configMapKeyRef:
                  name: mongo-configmap
                  key: mongodb_url
---
apiVersion: v1
kind: Service
metadata:
  name: mongoexpress-service
spec:
  selector:
    app: mongoexpress
  type: NodePort
  ports:
    - port: 8081
      targetPort: 8081
      #nodePort: 30002
