apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: eks-k8s
  region: ap-south-1
  version: "1.23"
nodeGroups:
  - name: ng-1
    instanceType: t2.medium
    maxSize: 2
    minSize: 1
    volumeSize: 30
    volumeType: gp3
    ssh:
      allow: true
  - name: ng-2
    instanceType: t2.medium
    desiredCapacity: 2
    volumeSize: 30
    volumeType: gp3
    ssh:
      allow: true
