apiVersion: v1
kind: Pod
metadata:
  name: p1
spec:
  containers:
  - name: c1
    image: alpine
    args:
    - /bin/sh
    - -c
      #- touch /tmp/healthy; sleep 30; rm -f /tmp/healthy; sleep 600
    - sleep 10; touch /1.txt; sleep 20; rm -f 1.txt; sleep 100
    livenessProbe:
      exec:
        command:
        - ls
        - -l
        - 1.txt
      initialDelaySeconds: 12
      periodSeconds: 5
