apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: sp-work
  name: sp-work
spec:
  containers:
  - image: nginx
    name: sp-work
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}



#ubuntu@node1:~$ sudo su
#root@node1:/home/ubuntu# cd /etc/kubernetes/manifests/
#root@node1:/etc/kubernetes/manifests# ls
#root@node1:/etc/kubernetes/manifests# vim sp-work.yaml
#root@node1:/etc/kubernetes/manifests# ls
#sp-work.yaml
#root@node1:/etc/kubernetes/manifests#
#ubuntu@manager:~/k8s/static-pods/sp-default-loc$ kubectl get pods
#NAME            READY   STATUS    RESTARTS   AGE
#sp-work-node1   1/1     Running   0          12s

#root@node1:/etc/kubernetes/manifests# ls
#sp-work.yaml
#root@node1:/etc/kubernetes/manifests# rm sp-work.yaml
#root@node1:/etc/kubernetes/manifests# ls
#root@node1:/etc/kubernetes/manifests#
#ubuntu@manager:~/k8s/static-pods/sp-default-loc$ kubectl get pods
#No resources found in default namespace.

