apiVersion: v1
kind: Pod
metadata:
  name: p1
  labels:
    app: myapp
spec:
  containers:
  - name: c1
    image: nginx:latest
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: pod-serv
spec:
  selector:
    app: myapp
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30004
