apiVersion: v1
kind: ReplicationController
metadata:
  name: rc1
  labels:
    app: myapp
spec:
  replicas: 3
  selector:
    app: myapp
  template:
    metadata:
      labels:
         app: myapp
    spec:
     containers:
     - name: c1
       image: nginx:latest
       ports:
       - containerPort: 80
     #nodeName: node2 (every replica is created on node2 only)
     affinity:
       nodeAffinity:
         requiredDuringSchedulingIgnoredDuringExecution:
           nodeSelectorTerms:
           - matchExpressions:
             - key: zone
               operator: In
               values:
               - aaa

---
apiVersion: v1
kind: Service
metadata:
  name: rc-serv
spec:
  selector:
    app: myapp
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30002
