apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rs22
  labels:
    app: myapp
    app1: dev
spec:
  replicas: 3
  selector:
    matchExpressions:
    - key: app
      operator: In
      values:
      - myapp
    - key: app1
      operator: NotIn
      values: [test]
      #- key: app1
      #operator: In
      #values: [dev]
  template:
    metadata:
      labels:
         app: myapp
         app1: dev
    spec:
     containers:
     - name: c1
       image: nginx:latest
       ports:
       - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: rs22-serv
spec:
  selector:
    app: myapp
    app1: dev
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30012

