apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rs1
  labels:
    app: myapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
         app: myapp
    spec:
     containers:
     - name: c1
       image: nginx:latest
       ports:
       - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: rs-serv
spec:
  selector:
    app: myapp
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30001

