apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: p1
  name: p1
spec:
  containers:
  - args:
    - "sleep"
    - "1000"
    image: busybox
    name: p1
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
