apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: htp
  name: htp
spec:
  containers:
  - image: httpd
    name: htp
    ports:
    - containerPort: 80
    volumeMounts:
    - name: vol1
      mountPath: /vol1
  volumes:
  - name: vol1
    configMap:
      name: cmap
      ## An array of keys from the ConfigMap to create as files
      # in cmap keys are file1 and file2 
      items:
      - key: file1
        path: f1
      - key: file2
        path: f2

        #ubuntu@manager:~/k8s/configmap/wp-sql-config-vol$ kubectl exec -it htp -- bash
        #root@htp:/usr/local/apache2# cd /vol1/
        #root@htp:/vol1# ls
        #f1  f2
        #root@htp:/vol1#

