apiVersion: v1
kind: Pod
metadata:
  name: p1
spec:
  containers:
    - name: c1
      image: ubuntu
      command: ["/bin/bash"]
      args: ["-c","sleep 5;mkdir mntvol1;cd /mntvol1;touch 1.txt;echo hello>1.txt;sleep 1000"]
      volumeMounts:
        - name: os-volume
          mountPath: /mntvol1
    - name: c2
      image: alpine
      command: ["sh"]
      args: ["-c","sleep 5;mkdir mntvol1;cd /mntvol1;echo hii>1.txt;sleep 1000" ]
      volumeMounts:
        - name: os-volume
          mountPath: /mntvol1
  volumes:
    - name: os-volume
      emptyDir: {}
