apiVersion: v1
kind: Pod
metadata:
  name: p1
  labels:
    app: p1
spec:
  volumes:
  - name: vol1
    emptyDir: {}
  containers:
  - name: c1
    image: nginx
    ports:
    - containerPort: 80
    volumeMounts:
    - name: vol1
      mountPath: /usr/share/nginx/html
  - name: c2
    image: alpine
    command: ["sh","-c","mkdir vol12;cd vol12;touch index.html;echo '</h1>hello</h1>' > index.html;sleep 10000"]
    volumeMounts:
    - name: vol1
      mountPath: /vol12
---
apiVersion: v1
kind: Service
metadata:
  name: p1-serv
spec:
  selector:
   app: p1
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30003

