apiVersion: v1
kind: Pod
metadata:
  name: p1
spec:
  containers:
  - name: c1
    image: nginx
    ports:
    - containerPort: 80
  tolerations:
   - key: "node-role.kubernetes.io/control-plane"
     operator: "Equal"     
     effect: "NoSchedule"
