apiVersion: v1
kind: Pod
metadata:
  name: pd1
spec:
  containers:
  - name: con1
    image: nginx
    ports:
    - containerPort: 80
  nodeSelector:
    zone: aaa
  tolerations:
  - key: color #node-role.kubernetes.io/control-plane
    operator: Equal
    value: green
    effect: NoSchedule
