apiVersion: v1
kind: Pod
metadata:
  name: pd1
spec:
  containers:
  - name: con1
    image: nginx
    ports:
    - containerPort: 80
  tolerations:
          #- key: node-role.kubernetes.io/control-plane
          #operator: Exists
          #effect: NoSchedule
  - key: zone
    operator: Equal
    value: aaa
    effect: NoSchedule
  - key: zone
    operator: Equal
    value: bbb
    effect: NoSchedule
