apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod
  name: pod1
spec:
  containers:
  - name: p1
    image: nginx
    resources: {}
  tolerations:
  - key: zone
    operator: Equal
    value: aaa
    effect: NoExecute

