apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  containers:
  - image: nginx:1.19.0
    name: test-pod
    ports:
    - containerPort: 80
    volumeMounts:
    - name: mntvol
      mountPath: /usr/share/nginx/html/index.html
      subPath: index.html
  volumes:
  - name: mntvol
    downwardAPI:
      items:
      - path: index.html
        fieldRef:
          fieldPath: metadata.namespace
