apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep1
  labels:
    app: app-dep1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app1
      env: dev
  template:
    metadata:
      labels:
        app: app1
        env: dev
    spec:
       containers:
       - name: c1
         image: nginx
         ports:
         - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: dep-serv
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30001
  selector:
    app: app-dep1  
