apiVersion: v1
kind: Pod
metadata:
  name: prac-pod
spec:
  containers:
    - name: c1
      image: jenkins/jenkins:lts
      ports:
        - containerPort: 8080
    - name: c2
      image: nginx
      ports:
        - containerPort: 80
