apiVersion: v1
kind: Pod
metadata:
  name: multi-cont-pod
  labels:
    app: ngin-jenk
spec:
  containers:
  - name: c1
    image: nginx
    ports:
    - containerPort: 80
  - name: c2
    image: jenkins/jenkins:lts
    ports:
    - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: multi-cont-serrvice
spec:
  selector:
    app: ngin-jenk
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30001
    name: nginx-port
  - port: 90
    targetPort: 8080
    nodePort: 30002
    name: jenk-port
