apiVersion: v1
kind: Pod
metadata:
  name: pod-node-sec
spec:
  containers:
  - name: c1
    image: nginx
    ports:
    - containerPort: 80
  - name: c2
    image: jenkins/jenkins:lts
    ports:
    - containerPort: 8080
  nodeSelector: 
    sony: bowbow

