apiVersion: v1
kind: Pod
metadata:
  name: os-pod
spec:
  containers:
    - name: c1
      image: ubuntu
      command: ["/bin/bash"]
      args: ["-c","sleep 20;touch 1.txt;sleep 1000"]
      volumeMounts:
        - name: os-volume
          mountPath: /mntvol1
    - name: c2
      image: alpine
      #command: ["sh"]
      #args: ["-c","sleep 10;touch 2.txt;sleep 1000" ]
      command: ["sh", "-c"]
      args:
      - sleep infinity
      volumeMounts:
        - name: os-volume
          mountPath: /mntvol1
  volumes:
    - name: os-volume
      emptyDir: {}
