apiVersion: v1
kind: Pod
metadata:
  name: pod3
  labels:
    app: tomcat
spec:
  containers:
  - name: c2
    image: jenkins/jenkins:lts
    ports:
    - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: pod3-service
spec:
  selector:
    app: tomcat
  type: NodePort
  ports:
  - port: 8080
    nodePort: 30001
    name: tmport

