apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: p1
  name: p1
spec:
  containers:
  - image: nginx
    name: p1
    ports:
    - containerPort: 80
    volumeMounts:
    - name: vol1
      mountPath: /usr/share/nginx/html
    - name: vol2
      mountPath: /vol2
  volumes:
  - name: vol1
    secret:
      secretName: sec-vol
      items:
      - key: index.html
        path: index.html
  - name: vol2
    secret:
      secretName: sec-vol
      
---
apiVersion: v1
kind: Service
metadata:
  name: pod-serv
spec:
  selector:
    run: p1
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30006
