apiVersion: v1
kind: Pod
metadata:
  name: ds-master
spec:
  containers:
  - name: con1
    image: nginx
  tolerations:
  - key: node-role.kubernetes.io/control-plane
    operator: Exists
    effect: NoSchedule
