apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: p1
  name: p1
spec:
  containers:
  - image: ubuntu
    name: c1
    command: ["bash","-c","sleep 10000"]
  - image: jenkins/jenkins:lts
    name: c2
    ports:
    - containerPort: 8080

      #ubuntu@manager:~/k8s/securitycontext$ kubectl exec -it p1 -c c1 -- bash
      #root@p1:/# whoami
      #root
      #root@p1:/#

      #ubuntu@manager:~/k8s/securitycontext$ kubectl exec -it p1 -c c2 -- bash
      #jenkins@p1:/$ whoami
      #jenkins
      #jenkins@p1:/$


