apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-dep
  labels:
    app: httpd
spec:
  replicas: 1
  selector:
    matchLabels:
       app: httpd
  template:
    metadata:
      name: httpd-pod
      labels:
        app: httpd
    spec:
      containers:
        - name: httpd-container
          image: httpd
          ports:
            - containerPort: 80
          volumeMounts: 
            - name: index-html
              mountPath: /usr/local/apache2/htdocs/ 
      volumes:
        - name: index-html
          configMap: 
            name: httpd-configmap 
---
apiVersion: v1
kind: Service
metadata:
  name: httpd-service
  labels:
    app: httpd-dep-service
spec:
  selector:
    app: httpd
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30002
