apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: p1
  name: p1
spec:
  containers:
  - image: nginx
    name: p1
    ports:
    - containerPort: 80
    volumeMounts:
    - name: vol1
      mountPath: /usr/share/nginx/html
  volumes:
  - name: vol1
    configMap:
      name:  httpd-configmap
      items:
      - key: index1.html
        path: index.html
---
apiVersion: v1
kind: Service
metadata:
  name: ng-serv
spec:
  selector:
    run: p1
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30002
