apiVersion: v1
kind: LimitRange
metadata:
  name: lm-devns
  namespace: dev
spec:
   limits:
   - default:
       cpu: 200m
       memory: 512Mi
     defaultRequest:
       cpu: 100m
       memory: 256Mi
     type: Container
