apiVersion: v1
kind: ResourceQuota
metadata:
  name: resquota-devns
  namespace: dev
spec:
  hard:
    pods: 4
    services: 3
    replicationcontrollers: 4
    secrets: 4
    loadbalancers: 2
    configmaps: 2
    persistentvolumeclaims: 2
    requests.cpu: 1
    requests.memory: 1Gi
    limits.cpu: 2
    limits.memory: 2Gi

 


    #$ kubectl describe ns dev

